# Generated by Django 4.0.6 on 2022-07-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mc_donalds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='amount',
        ),
        migrations.AddField(
            model_name='productorder',
            name='_amount',
            field=models.IntegerField(db_column='amount', default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mc_donalds.staff'),
        ),
    ]
